name: Deploy React Frontend to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6355DAC29B5D4FC49B550746D929B146 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF21D112057D4F4A9E287C61FDB45F92 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F17F34BEF686424A82BEAA730069D71A }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: protein-frontend-karthick
          package: build
